services:
  sonarqube:
    image: sonarqube/sonarqube:latest
    container_name: sonar
    ports:
      - "9000:9000"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

# nofile: 컨테이너가 열 수 있는 파일의 최대 개수를 설정합니다.
# soft: "262144": 소프트 리미트로 설정된 값입니다. 사용자가 변경할 수 있는 한계입니다.
# hard: "262144": 하드 리미트로 설정된 값입니다. 시스템 전체의 한계로, 이보다 높게 설정할 수 없습니다.
# 이 설정은 SonarQube가 많은 파일을 처리할 수 있도록 리소스 제한을 늘려주는 역할을 합니다.
